name: ricky
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  google_fonts: ^2.1.0
  easy_localization: ^3.0.0
  go_router: 3.0.3
  freezed_annotation: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.5
  freezed: 2.0.3
  mockito: ^5.1.0



flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/
